name: 'Generate pip freeze file.'

inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        python-bin="python3"
        [[ "${{ python-version }}" == "2.7" ]] && python-bin="python"
        ./venv/bin/${python-bin} -m pip freeze > requirements.txt
      shell: bash
