environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

install:
  # Check that we have the expected version and architecture for Python
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe -c \"import struct; print(struct.calcsize('P') * 8)\""

  - ps: Invoke-WebRequest -Uri https://raw.githubusercontent.com/pypa/virtualenv/master/virtualenv.py -OutFile .\\virtualenv.py
  - ps: Invoke-WebRequest -Uri https://bootstrap.pypa.io/get-pip.py -OutFile .\\get-pip.py
  - "%PYTHON%\\python.exe virtualenv.py --clear --no-setuptools --no-pip --no-wheel venv"
  - ".\\venv\\Scripts\\python.exe get-pip.py"
  - ".\\venv\\Scripts\\python.exe -m pip install -U setuptools pip flake8"
  - ".\\venv\\Scripts\\python.exe setup.py setup_test"

build: off

test_script:
  - ".\\venv\\Scripts\\python.exe -m pytest"
  - ".\\venv\\Scripts\\python.exe -m flake8 make_clean.py test/"
